name: Trigger auto deployment for letssqsapp

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/letssqsapp-AutoDeployTrigger-60919157-cd97-4593-9eca-064a23dfc664.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: firstappacr001.azurecr.io
          username: ${{ secrets.LETSSQSAPP_REGISTRY_USERNAME }}
          password: ${{ secrets.LETSSQSAPP_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: firstappacr001.azurecr.io/letssqsapp:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.LETSSQSAPP_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n letssqsapp -g LetsFirstAppRG --server firstappacr001.azurecr.io --username  ${{ secrets.LETSSQSAPP_REGISTRY_USERNAME }} --password ${{ secrets.LETSSQSAPP_REGISTRY_PASSWORD }}
            az containerapp update -n letssqsapp -g LetsFirstAppRG --image firstappacr001.azurecr.io/letssqsapp:${{ github.sha }}
